<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="aspirenav145" name="com.pure.selfservice.testscripts.PB_Household" tests="3" failures="0" timestamp="23 Apr 2018 15:01:29 GMT" time="879.819" errors="3">
  <testcase name="TC_044" time="290.892" classname="com.pure.selfservice.testscripts.PB_Household">
    <error type="java.lang.Exception" message="Error while verifying edit and delete button of Added Item in Outside Home : java.lang.Exception: Antique Furniture - Added Item is not found">
      <![CDATA[java.lang.Exception: Error while verifying edit and delete button of Added Item in Outside Home : java.lang.Exception: Antique Furniture - Added Item is not foundat com.pure.selfservice.pages.AddContentsCoverPage.verifyDeleteAndEditBtnInOutsideHome(AddContentsCoverPage.java:1096)at com.pure.selfservice.testscripts.PB_Household.TC_044(PB_Household.java:2454)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- TC_044 -->
  <testcase name="TC_043" time="260.663" classname="com.pure.selfservice.testscripts.PB_Household">
    <error type="java.lang.Exception" message="Error while verifying edit and delete button of Added Item in Within Home : java.lang.Exception: Awnings - Added Item is not found">
      <![CDATA[java.lang.Exception: Error while verifying edit and delete button of Added Item in Within Home : java.lang.Exception: Awnings - Added Item is not foundat com.pure.selfservice.pages.AddContentsCoverPage.verifyDeleteAndEditBtnInWithinHome(AddContentsCoverPage.java:1061)at com.pure.selfservice.testscripts.PB_Household.TC_043(PB_Household.java:2351)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- TC_043 -->
  <testcase name="TC_045" time="328.264" classname="com.pure.selfservice.testscripts.PB_Household">
    <error type="java.lang.Exception" message="Error while Expand And Collapse The Acadians : org.openqa.selenium.WebDriverException: unknown error: Element &lt;a aria-expanded=&quot;false&quot; data-parent=&quot;#accordion&quot; data-toggle=&quot;collapse&quot; href=&quot;#C2__C1__Additional-covers&quot; class=&quot;disablerow&quot;&gt;...&lt;/a&gt; is not clickable at point (674, 560). Other element would receive the click: &lt;h4 class=&quot;panel-title&quot;&gt;...&lt;/h4&gt;
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 44 milliseconds
Build info: version: &#039;3.4.0&#039;, revision: &#039;unknown&#039;, time: &#039;unknown&#039;
System info: host: &#039;ASPIRENAV145&#039;, ip: &#039;192.168.71.196&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_77&#039;
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73), userDataDir=C:\Users\RANJIT~1.MAD\AppData\Local\Temp\scoped_dir17024_30835}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=65.0.3325.181, browserConnectionEnabled=false, nativeEvents=true, webdriver.remote.sessionid=3781e7e501b3c66657b49896b79e1a4c, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 3781e7e501b3c66657b49896b79e1a4c">
      <![CDATA[java.lang.Exception: Error while Expand And Collapse The Acadians : org.openqa.selenium.WebDriverException: unknown error: Element <a aria-expanded="false" data-parent="#accordion" data-toggle="collapse" href="#C2__C1__Additional-covers" class="disablerow">...</a> is not clickable at point (674, 560). Other element would receive the click: <h4 class="panel-title">...</h4>  (Session info: chrome=65.0.3325.181)  (Driver info: chromedriver=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73),platform=Windows NT 10.0.10240 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 44 millisecondsBuild info: version: '3.4.0', revision: 'unknown', time: 'unknown'System info: host: 'ASPIRENAV145', ip: '192.168.71.196', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_77'Driver info: org.openqa.selenium.remote.RemoteWebDriverCapabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=XP, acceptSslCerts=false, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.35.528161 (5b82f2d2aae0ca24b877009200ced9065a772e73), userDataDir=C:\Users\RANJIT~1.MAD\AppData\Local\Temp\scoped_dir17024_30835}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=65.0.3325.181, browserConnectionEnabled=false, nativeEvents=true, webdriver.remote.sessionid=3781e7e501b3c66657b49896b79e1a4c, locationContextEnabled=true, cssSelectorsEnabled=true}]Session ID: 3781e7e501b3c66657b49896b79e1a4cat com.pure.selfservice.pages.AddContentsCoverPage.verifyExpandAndCollapseTheAcadians(AddContentsCoverPage.java:1811)at com.pure.selfservice.testscripts.PB_Household.TC_045(PB_Household.java:2539)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)at java.util.concurrent.FutureTask.run(Unknown Source)at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)at java.lang.Thread.run(Unknown Source)]]>
    </error>
  </testcase> <!-- TC_045 -->
</testsuite> <!-- com.pure.selfservice.testscripts.PB_Household -->
